# SMPL CONSTANT

SMPLX_JOINTS = (
    "Pelvis",
    "L_Hip",
    "R_Hip",
    "Spine_1",
    "L_Knee",
    "R_Knee",
    "Spine_2",
    "L_Ankle",
    "R_Ankle",
    "Spine_3",
    "L_Foot",
    "R_Foot",
    "Neck",
    "L_Collar",
    "R_Collar",
    "Head",
    "L_Shoulder",
    "R_Shoulder",
    "L_Elbow",
    "R_Elbow",
    "L_Wrist",
    "R_Wrist",  # body joints
    "Jaw",
    "L_Eye",
    "R_Eye",  # face joints
    "L_Index_1",
    "L_Index_2",
    "L_Index_3",
    "L_Middle_1",
    "L_Middle_2",
    "L_Middle_3",
    "L_Pinky_1",
    "L_Pinky_2",
    "L_Pinky_3",
    "L_Ring_1",
    "L_Ring_2",
    "L_Ring_3",
    "L_Thumb_1",
    "L_Thumb_2",
    "L_Thumb_3",  # left hand joints
    "R_Index_1",
    "R_Index_2",
    "R_Index_3",
    "R_Middle_1",
    "R_Middle_2",
    "R_Middle_3",
    "R_Pinky_1",
    "R_Pinky_2",
    "R_Pinky_3",
    "R_Ring_1",
    "R_Ring_2",
    "R_Ring_3",
    "R_Thumb_1",
    "R_Thumb_2",
    "R_Thumb_3",  # right hand joints
)
